Vagrant.configure("2") do |config|
  config.vm.define "package" do |web|
    config.vm.box = "centos/7"
    config.vm.box_version = "2004.01" 
    config.vm.hostname = 'package'
    config.vm.network :private_network, ip: "192.168.56.10"
    config.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end
  end
end