Vagrant.configure("2") do |config|
  config.vm.define "systemd" do |systemd|
    systemd.vm.box = "centos/7"
    systemd.vm.box_version = "2004.01"
    systemd.vm.hostname = 'systemd'
    systemd.vm.network :private_network, ip: "192.168.56.10"
    systemd.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end
    systemd.vm.provision "ansible" do |ansible|
        ansible.compatibility_mode = "2.0"
        ansible.playbook = "main.yml"
      end
  end
  config.vm.provision "shell", inline: <<-SHELL
    yum -y install epel-release && yum -y install spawn-fcgi php php-climod_fcgid httpd
  SHELL
end