Vagrant.configure("2") do |config|
  config.vm.define "web" do |web|
    web.vm.box = "generic/ubuntu2204"
    web.vm.hostname = 'web'
    web.vm.network :private_network, ip: "192.168.56.10"
    web.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end
    web.vm.provision "ansible" do |ansible|
        ansible.compatibility_mode = "2.0"
        ansible.playbook = "main.yml"
      end
  end
end