Vagrant.configure(2) do |config|
    config.vm.box = "generic/ubuntu2204"
  
    config.vm.provision "ansible" do |ansible|
      #ansible.verbose = "vvv"
      ansible.compatibility_mode = "2.0"
      ansible.playbook = "provisioning/playbook.yml"
      ansible.become = "true"
    end
  
    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 1
    end
  
    config.vm.define "backup" do |backup|
      backup.vm.network "private_network", ip: "192.168.56.10"
      backup.vm.hostname = "backup"
      backup.vm.disk :disk, size: "2GB", name: "extra_storage1"
    end
  
    config.vm.define "client" do |client|
      client.vm.network "private_network", ip: "192.168.56.15"
      client.vm.hostname = "client"
    end
  
  end
  