MACHINES = {
  :"pam" => {
              :box_name => "generic/ubuntu2204",
              :cpus => 2,
              :memory => 1024,
              :ip => "192.168.57.10",
            }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.provision "file", source: "login.sh", destination: "/tmp"
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.network "private_network", ip: boxconfig[:ip]
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.box_version = boxconfig[:box_version]
      box.vm.host_name = boxname.to_s

      box.vm.provider "virtualbox" do |v|
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
      end
      box.vm.provision "shell", inline: <<-SHELL
      sudo -i
      useradd otusadm && sudo useradd otus
      echo "otusadm:Otus2024!" | chpasswd && echo "otus:Otus2024!" | chpasswd
      groupadd -f admin
      usermod otusadm -a -G admin && usermod root -a -G admin && usermod vagrant -a -G admin
      cp /tmp/tmp /usr/local/bin/login.sh
      chmod +x /usr/local/bin/login.sh
      sed -i '7 i\ auth required pam_exec.so debug /usr/local/bin/login.sh' /etc/pam.d/sshd
      sed -i 's/^PasswordAuthentication.*$/PasswordAuthentication yes/' /etc/ssh/sshd_config
      systemctl restart sshd.service
      date 051112302024.00
  	  SHELL
    end
  end
end
