Vagrant.configure("2") do |config|
  config.vm.define "mdadm" do |mdadm|
    mdadm.vm.box = "generic/ubuntu2204"
    mdadm.vm.hostname = 'mdadm'
    mdadm.vm.network :private_network, ip: "192.168.56.10"
    mdadm.vm.disk :disk, size: "5GB", name: "extra_storage1"
    mdadm.vm.disk :disk, size: "5GB", name: "extra_storage2"
    mdadm.vm.disk :disk, size: "5GB", name: "extra_storage3"
    mdadm.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end
    config.vm.provision "shell", inline: <<-SHELL
    sudo -i
    mdadm --create /dev/md1 -l 5 -n 3 /dev/sd{b,c,d}
    echo "DEVICE partitions" > /etc/mdadm/mdadm.conf
    mdadm --detail --scan --verbose | awk '/ARRAY/ {print}' >> /etc/mdadm/mdadm.conf
    parted -s /dev/md1 mklabel gpt
    parted /dev/md1 mkpart primary ext4 0% 20%
    parted /dev/md1 mkpart primary ext4 20% 60%
    parted /dev/md1 mkpart primary ext4 60% 100%
    sleep 5
    for i in $(seq 1 3); do mkfs.ext4 /dev/md1p$i; done
    mkdir -p /mnt/raid{1,2,3}
    for i in $(seq 1 3); do mount /dev/md1p$i /mnt/raid$i; done
    for i in $(seq 1 3); do U="$(blkid -s UUID -o value /dev/md1p$i)"; echo "UUID="$U" /mnt/raid$i ext4 defaults 0 1" | tee -a /etc/fstab; done
    findmnt -t ext4
    SHELL
  end
end
