Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.provider "virtualbox" do |v|
   v.memory = 2048
   v.cpus = 2
  end

config.vm.provision "shell", reboot:1, inline: <<-SHELL
     sudo apt-get update && sudo apt-get dist-upgrade -yq
  SHELL
config.vm.provision "shell", inline: <<-SHELL
     sudo apt install build-essential libncurses-dev bison flex libssl-dev libelf-dev fakeroot -y
     cd /tmp && wget https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.10.199.tar.xz
     tar -xf linux-5.10.199.tar.xz && cd /tmp/linux-5.10.199
     make olddefconfig
     make localmodconfig
     scripts/config --disable CONFIG_DEBUG_INFO_BTF
     scripts/config --disable SYSTEM_REVOCATION_KEYS
     scripts/config --disable SYSTEM_TRUSTED_KEYS
     fakeroot make -j2
     sudo make modules_install
     sudo make install
     sudo reboot
  SHELL
end