Vagrant.configure(2) do |config|
    config.vm.box = "generic/ubuntu2204"
  
    config.vm.provision "ansible" do |ansible|
      #ansible.verbose = "vvv"
      ansible.compatibility_mode = "2.0"
      ansible.playbook = "provisioning/playbook.yml"
      ansible.become = "true"
    end
  
    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
    end
  
    config.vm.define "web" do |web|
      web.vm.network "private_network", ip: "192.168.56.10"
      web.vm.hostname = "web"
    end
  
    config.vm.define "log" do |log|
      log.vm.network "private_network", ip: "192.168.56.15"
      log.vm.hostname = "log"
    end
  
  end
  